#version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: AdWavePostgres
    environment:
      POSTGRES_DB: AdWaveDB
      POSTGRES_USER: AdWaveAdmin
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always  # Configura o contêiner para reiniciar automaticamente

volumes:
  pgdata:
    driver: local
    image: postgres:latest
    container_name: AdWave_postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - AdWave_network
      

  # Outros serviços (como back-end e front-end) podem ser adicionados aqui

